rvm:
  - 2.0
  - 2.1.1
before_script:
  - cp test/config/database.yml.example test/config/database.yml
  - mysql -e 'create database global_uid_test;'
  - mysql -e 'create database global_uid_test_id_server_1;'
  - mysql -e 'create database global_uid_test_id_server_2;'
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
bundler_args: --no-deployment
script: "rake test"
