cache: bundler
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
bundler_args: --no-deployment
script: "bundle exec rake test"
matrix:
  allow_failures:
    - gemfile: gemfiles/rails5.2.gemfile
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails4.2.gemfile
branches:
  only: master
